# Generated by Django 4.2.7 on 2025-09-21 15:41

from django.db import migrations
import quickbites.models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', quickbites.models.UserManager()),
            ],
        ),
    ]
